name: Run tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  ts-tests:
    runs-on: ubuntu-latest
    uses: actions/checkout@v4

    steps:
      - name: Dependency installation
        run: npm i

      - name: run tests
        run: npx jest
